# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Columbia', 'Columbia'), ('Greenville', 'Greenville'), ('Spartanburg', 'Spartanburg')], default='Greenville', max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='listing_photos', verbose_name='Listing Photo')),
                ('listing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craigs_list.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Columbia', 'Columbia'), ('Greenville', 'Greenville'), ('Spartanburg', 'Spartanburg')], default='Greenville', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craigs_list.Category')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craigs_list.SubCategory'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
